INSERT INTO exchange (ID, ORIGINCURRENCY, DESTINATIONCURRENCY, VALUE) VALUES (1, 'USD', 'SOL', 4);
INSERT INTO exchange (ID, ORIGINCURRENCY, DESTINATIONCURRENCY, VALUE) VALUES (2, 'EUR', 'SOL', 5);
INSERT INTO exchange (ID, ORIGINCURRENCY, DESTINATIONCURRENCY, VALUE) VALUES (3, 'EUR', 'USD', 2);