DROP TABLE IF EXISTS exchange;
CREATE TABLE exchange (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ORIGINCURRENCY VARCHAR(10) NOT NULL,
    DESTINATIONCURRENCY VARCHAR(10) NOT NULL,
    VALUE float NOT NULL,
    PRIMARY KEY (id)
);